### PR TITLE
skip bakcup of hotplug-volume pod

### PR DESCRIPTION
**Pull request by muxuelanKK**
skip bakcup of hotplug-volume pod

### CODE REVIEW

**Comment by ShellyKa13** [comment]
Hi @muxuelanKK !
This is interesting I wonder how did you come up with the need for this PR,
Have you noticed issues with restore of vm with hotplug because the hotplug pod exists?

**Comment by muxuelanKK** [comment]
> Hi @muxuelanKK ! This is interesting I wonder how did you come up with the need for this PR, Have you noticed issues with restore of vm with hotplug because the hotplug pod exists?

I just happened to encounter this phenomenon. And I think we needn't to backup up vmi and pods(eg launcher pod、hp-voulme pod)，we just bakcup up vm and volumes, because when restoring kubevirt will create vmi and launcher pod based on vm.

**Comment by ShellyKa13** [comment]
Thanks @muxuelan for your observation as you stated there is no need to restore virt-launcher pod and hotplug pod since they will be created with the vm start.
Regarding the virt-launcher we already deal with this in pod_restore_item_action. We decided to still backup this pod and just skip its restore.
Regarding the hotplug pod we did miss to skip it too, and although it is tested and doesnt seem to do actually cause any failure in restoring it, I agree its better to skip its restore. So I would suggest to just change this line: https://github.com/kubevirt/kubevirt-velero-plugin/blob/main/pkg/plugin/pod_restore_item_action.go#L45 to:
`LabelSelector: "kubevirt.io in (virt-launcher, hotplug-disk)",`
We prefer to keep in the backup everything that was in the namespace/cluster at the backup time.

**Comment by ShellyKa13** [comment]
Hi @muxuelan since you didnt respond for a while Im closing this PR in favor of https://github.com/kubevirt/kubevirt-velero-plugin/pull/262

**Pull request closed without merging**
