### PR TITLE
Update cdi, kv

### PR DESCRIPTION
**Pull request by brybacki**
**What this PR does / why we need it**:

Update CDI and KV

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt-velero-plugin/45/pull-kvp-functional-test/1504024106427748352/artifacts/pods/1_kvp-e2e-tests-8w67d_importer-test-dv-importer.log
sounds like https://github.com/kubevirt/containerized-data-importer/issues/2160

**Comment by brybacki** [comment]
> 

Yes, but this time is happens third time in a row in the same test.

**Comment by akalenyu** [comment]
> > 
> 
> Yes, but this time is happens third time in a row in the same test.

Think its related to CDI bump? maybe try bump to something more stable like 1.43.z?

**Comment by brybacki** [comment]
> > > 
> > 
> > 
> > Yes, but this time is happens third time in a row in the same test.
> 
> Think its related to CDI bump? maybe try bump to something more stable like 1.43.z?

I'll try 1.40 again

**Pull request closed without merging**
