### PR TITLE
Bump kubevirtci to 2205231118-f12b50e

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:
2205231118-f12b50e
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/lgtm
lets see if the rook problem from https://github.com/kubevirt/kubevirt/pull/7783 are here as well..

**Comment by akalenyu** [comment]
one success, lets check again
/test pull-kvp-functional-test

**Comment by brybacki** [comment]
Is it fix or are we lucky? Either way it looks better than previous version .

**Pull request merged**
